# Unique name for this workflow
name: DxTemplates - Just ScratchOrg Creation

# Definition when the workflow should run

on:
  workflow_dispatch:
    inputs:
     scratch-org_name: 
      #friendly name to the scratch-org which needs to be created
      default: 'scratch-org'
      required: true
     scratch-org_username:
      default: 'username@dextara.com'
      required: true
     scratch-org_email:
      default: 'personemail@dextara.com'
      required: true

# Jobs to be executed

jobs:

 environment-setup:
  
    name: environment-setup
    runs-on: ubuntu-latest
    
    steps:
    
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v2
        
      # Cache node_modules to speed up the process
      - name: Setup Node Environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          
 validate:
    name: Scratchorg creation
    needs: [environment-setup]
    runs-on: ubuntu-latest
    # if: github.event == 'push'
    steps:
    
    # Install Salesforce CLI
      - name: Install Salesforce CLI
        env:
          GITHUB_PATH: ~/Git/bin
        run: |
              wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
              sudo mkdir ~/sfdx-cli
              sudo tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx-cli --strip-components 1
              export PATH=$PATH:~/sfdx-cli/bin
              echo "~/sfdx-cli/bin" >> $GITHUB_PATH
              sudo chmod -R 777 ~/sfdx-cli
              sfdx --version
            
    # Run Salesforce CLI Scanner For Security checks
      - name: 'Check for SFDX Update'
        run: sfdx update

    # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v2

    # Connect with Salesforce ORG
      - name: 'Connect with Salesforce ORG'
        working-directory: .github/jwt/
        run: sfdx auth:jwt:grant --clientid ${{ secrets.CONNECTED_APP_CONSUMER_KEY_DEVHUB }} --jwtkeyfile server.key --username ${{ secrets.HUB_ORG_USERNAME }} -d --instanceurl ${{ secrets.SFDC_HOST_LOGIN }}
        
     # Run Salesforce CLI Scanner For Security checks _
      - name: 'List All ORGS'
        run: sfdx force:org:list
  
      # Create scratch org
      - name: 'Create scratch org'
        run: |
             echo 'y' | sfdx sf org create scratch --target-dev-hub ${{ secrets.HUB_ORG_USERNAME }} --definition-file config/project-scratch-def.json --set-default --duration-days 30 --name ${{github.event.inputs.scratch-org_name}} --username ${{github.event.inputs.scratch-org_username}} --admin-email ${{github.event.inputs.scratch-org_email}}
        
      - name: Change password
        run: sfdx force:user:password:generate --targetusername ${{github.event.inputs.scratch-org_username}}
                                   
      - name: Display user information
        id: display_user
        run: sfdx force:user:display --targetusername ${{github.event.inputs.scratch-org_username}} --json
